name: MasterDeployCI
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Create Plugin Directory
      run: mkdir -p Build/AssetsBridge
    - name: Copy Plugin Data
      run: rsync -av --exclude=.github/ --exclude=.git/ --exclude=README.md --exclude=AssetsBridge.zip ./ Build/AssetsBridge/
    - name: Zip Folder
      run: cd Build/ && zip -r release.zip .
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Build/AssetsBridge.zip